# Generated by Django 5.1.3 on 2024-11-18 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comform', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comform',
            name='image',
        ),
        migrations.RemoveField(
            model_name='comform',
            name='price',
        ),
        migrations.AddField(
            model_name='comform',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='uploads/attachments/'),
        ),
        migrations.AddField(
            model_name='comform',
            name='complain_title',
            field=models.CharField(default='complain_title', max_length=200),
        ),
        migrations.AddField(
            model_name='comform',
            name='department',
            field=models.CharField(default='General Department', max_length=100),
        ),
        migrations.AddField(
            model_name='comform',
            name='session',
            field=models.CharField(default='session', max_length=50),
        ),
        migrations.AlterField(
            model_name='comform',
            name='description',
            field=models.TextField(default='description'),
        ),
    ]
